### PR TITLE
feat: make font color consistent

### PR DESCRIPTION
**Pull request by BoYanZh**

### CODE REVIEW

**Review by Max-Herbold — DISMISSED** [review]
Looks better! (when did the default color become black? lol) I wonder here, would 
`marginTop: 1` or maybe 2 look better still?

**Comment by BoYanZh** [comment]
image

```
                style: {
                    color: "var(--channels-default)",
                    fontWeight: "bold",
                    fontFamily: "monospace",
                    fontSize: 11,
                    position: "relative",
                }
```

I use this style and looks good now.

**Review by Max-Herbold — APPROVED** [review]

**Comment by IamMully** [comment]
@Max-Herbold Please merge this PR 🙏 I was about to open an identical PR

**Review by IamMully — APPROVED** [review]
@Max-Herbold Please merge this PR 🙏 I was about to open an identical PR

**Pull request merged**
